//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KroApp.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KroApp.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FdcId,Name,Description,Category,LastUpdated
        ///1001,Apple,Red and sweet fruit,Fruit,2023-11-20T12:00:00Z
        ///1002,Carrot,Orange root vegetable,Vegetable,2023-11-19T10:30:00Z
        ///1003,Chicken,Broiler chicken meat,Meat,2023-11-18T08:45:00Z
        ///.
        /// </summary>
        internal static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FdcId,UserId,IngredientId,DateAdded,Quantity,ExpirationDate,Location,Notes
        ///1001,1,1,2023-11-20,2.5,2023-12-05,Fridge,Organic apples
        ///1002,1,2,2023-11-18,1.0,2023-12-01,Pantry,Locally grown
        ///1003,2,3,2023-11-17,3.0,2023-11-30,Freezer,Frozen chicken breast
        ///.
        /// </summary>
        internal static string UserIngredients {
            get {
                return ResourceManager.GetString("UserIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName,Email,NormalizedUserName,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount
        ///johndoe,john@example.com,JOHNDOE,JOHN@EXAMPLE.COM,True,hashedpassword,stamp1,concurrency1,1234567890,True,False,,True,0
        ///janedoe,jane@example.com,JANEDOE,JANE@EXAMPLE.COM,True,hashedpassword,stamp2,concurrency2,0987654321,True,False,,True,0
        ///.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
